### ISSUE TITLE
extends while running quickTour.lua fails

### ISSUE THREAD

**Issue by krusmir** [Yonaba/Lua-Class-System#1]
Hello,

It seems the extends functionality is not working (weird).  Using Lua 5.1 in MOAI interpreter

=============================== OUTPUT==============================

myVipAccount:deposit(1000)
print('myVipAccount current balance is',myVipAccount.balance,' the maximum balance is still ',myVipAccount.maximum_balance,'and I don\'t care!')

-- Now, the awesome stuff, we can still call the original deposit() method in the superclass Account
print('Calling the original deposit() method in the superclass from the subclass to make a deposit of 1 in the vipAccount')
myVipAccount:super('deposit',1)

=== Output === 

 Failed to run a sample.
Please report the following error to the author.

.\LCS.lua:51: bad argument #1 to 'pairs' (table expected, got nil)

Press Enter to run the next sample

**Comment by krusmir** [comment]
Previous error can be fixed by modifying the function checkForMethod(list) with the following:

```
local function checkForMethod(list)
  if list then
    for k,attr in pairs(list) do
      assert(type(attr)~='function','Cannot assign functions as members')
    end
  end
end
```

**Comment by Yonaba** [comment]
Hi,
Thanks reporting this. It should now be fixed with this [commit](https://github.com/Yonaba/Lua-Class-System/commit/3a0b82d21b65ca8f6e8f609414bc4f0078a623d2).
