### ISSUE TITLE
Instance Unique Identifiers

### ISSUE THREAD

**Issue by Xerosigma** [Yonaba/Lua-Class-System#8]
I'm trying to implement an equals method: objectInstance:Equals(otherInstance)

Comparing values should work fine, but say I wanted to check if their reference was equal, is this possible?

I was originally thinking of implementing a simple unique ID system using  math.randomseed and generating a unique ID on instance creation. But if there is something already in place for this, I may have missed it.

Thank you.

**Comment by Yonaba** [comment]
I am not sure I understand what you mean when saying _"check if references are equal"_, but provided that classes/objects are just regular Lua tables, using `==` operator actually compares the operands references.

``` lua
local LCS = require "LCS"

local Class = LCS.class()
function Class:equals(other)
    return self == other
end

objA = A()
objB = A()

print(objA:equals(objB)) --> false
print(objB:equals(objA)) --> false
print(objA:equals(objA)) --> true
print(objB:equals(objB)) --> true
```

**Comment by Xerosigma** [comment]
Gotcha, that helps.

Thank you.

**Comment by Yonaba** [comment]
You are welcome.
